#!/usr/bin/env bash
# Generate thin agent-specific pointers to the canonical prompts in docs/prompts/.
#
# Usage:
#   docs/prompts/setup-agent-commands.sh
#   docs/prompts/setup-agent-commands.sh --codex
#   docs/prompts/setup-agent-commands.sh --check [--codex]
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
MARKER="Generated by docs/prompts/setup-agent-commands.sh"

# command name : prompt file : argument hint
PROMPTS="
exercise:add-lecture-exercise.md:<exercise> - e.g. ex5forkexec, or \"lecture 2, ex3\"
lab:derive-lab-exercise.md:<lab>: <exercise> - e.g. \"util: find\" or \"syscall: trace\"
"

check=0
install_codex=0
fail=0

usage() {
  printf 'Usage: %s [--check] [--codex]\n' "${0#"$REPO"/}" >&2
}

for arg in "$@"; do
  case "$arg" in
    --check) check=1 ;;
    --codex) install_codex=1 ;;
    *) usage; exit 2 ;;
  esac
done

note() { printf '  %s\n' "$*"; }

body() {
  cat <<EOF
Read \`docs/prompts/$1\` in this repository and follow it exactly, including its verification step. That file is authoritative; this command only supplies the target.

**Target:** $2

If the target is empty, ask before doing anything else. Do not infer it from \`conf/lab.mk\` or recently edited files.
EOF
}

yaml_string() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

claude_stub() {
  local title
  title="$(head -1 "$REPO/docs/prompts/$1" | sed 's/^# Prompt: //')"
  printf '%s\n' '---'
  printf 'description: '; yaml_string "$title"; printf '\n'
  printf 'argument-hint: '; yaml_string "$2"; printf '\n'
  printf '%s\n\n' '---'
  printf '%s\n\n' '<!-- Generated by docs/prompts/setup-agent-commands.sh; do not edit. -->'
  body "$1" '$ARGUMENTS'
}

cursor_stub() {
  local title
  title="$(head -1 "$REPO/docs/prompts/$1" | sed 's/^# Prompt: //')"
  printf '<!-- %s; do not edit. -->\n\n' "$MARKER"
  printf '# %s\n\nArgument hint: `%s`\n\n' "$title" "$2"
  body "$1" 'whatever was typed after this command in the chat'
}

codex_stub() {
  local title
  title="$(head -1 "$REPO/docs/prompts/$1" | sed 's/^# Prompt: //')"
  printf '%s\n' '---'
  printf 'description: '; yaml_string "$title"; printf '\n'
  printf 'argument-hint: '; yaml_string "$2"; printf '\n'
  printf '%s\n\n' '---'
  printf '<!-- %s; do not edit. -->\n\n' "$MARKER"
  body "$1" '$ARGUMENTS'
}

display_path() {
  case "$1" in
    "$REPO"/*) printf '%s' "${1#"$REPO"/}" ;;
    *) printf '%s' "$1" ;;
  esac
}

emit() {
  local path="$1" dir tmp
  shift

  if [ "$check" = 1 ]; then
    if [ ! -f "$path" ]; then
      note "MISSING: $(display_path "$path")"
      fail=1
    elif ! diff -q <("$@") "$path" >/dev/null 2>&1; then
      note "STALE:   $(display_path "$path")"
      fail=1
    fi
    return
  fi

  dir="$(dirname "$path")"
  if ! mkdir -p "$dir" || ! tmp="$(mktemp "$dir/.agent-command.XXXXXX")"; then
    note "FAILED:  $(display_path "$path")"
    fail=1
    return
  fi
  if ! "$@" > "$tmp" || ! mv "$tmp" "$path"; then
    rm -f "$tmp"
    note "FAILED:  $(display_path "$path")"
    fail=1
    return
  fi
  note "wrote $(display_path "$path")"
}

sync_orphans() {
  local dir="$1" expected="$2" path
  [ -d "$dir" ] || return
  for path in "$dir"/*.md; do
    [ -e "$path" ] || continue
    grep -qF "$MARKER" "$path" || continue
    grep -qxF "$path" <<< "$expected" && continue
    if [ "$check" = 1 ]; then
      note "ORPHAN:  $(display_path "$path")"
      fail=1
    elif rm -f "$path"; then
      note "removed $(display_path "$path")"
    else
      note "FAILED:  $(display_path "$path")"
      fail=1
    fi
  done
}

claude_paths=""
cursor_paths=""
codex_paths=""

echo "== slash-command mirrors =="
while IFS=: read -r name file hint; do
  [ -n "$name" ] || continue
  hint="${hint## }"
  claude_path="$REPO/.claude/commands/$name.md"
  cursor_path="$REPO/.cursor/commands/$name.md"
  codex_path="$CODEX_HOME/prompts/$name.md"
  claude_paths+="$claude_path"$'\n'
  cursor_paths+="$cursor_path"$'\n'
  codex_paths+="$codex_path"$'\n'

  if [ ! -f "$REPO/docs/prompts/$file" ]; then
    note "NO SOURCE: docs/prompts/$file (referenced by /$name)"
    fail=1
    continue
  fi

  emit "$claude_path" claude_stub "$file" "$hint"
  emit "$cursor_path" cursor_stub "$file" "$hint"
  if [ "$install_codex" = 1 ]; then
    emit "$codex_path" codex_stub "$file" "$hint"
  fi
done <<< "$PROMPTS"

sync_orphans "$REPO/.claude/commands" "$claude_paths"
sync_orphans "$REPO/.cursor/commands" "$cursor_paths"
if [ "$install_codex" = 1 ]; then
  sync_orphans "$CODEX_HOME/prompts" "$codex_paths"
else
  echo "== codex =="
  note "Codex loads AGENTS.md automatically. Its custom prompts are user-level;"
  note "use --codex to install or check $CODEX_HOME/prompts."
fi

if [ "$check" = 1 ]; then
  if [ "$fail" = 0 ]; then
    echo "All selected mirrors current."
  else
    echo "Mirrors are stale; re-run without --check."
  fi
fi
exit "$fail"
